cp cmh_vcf_nolib.py ~/mybin/cmh_vcf_nolib
cp cmh_vcf.py ~/mybin/cmh_vcf
cp cmh_vcf_small_fast.py ~/mybin/cmh_vcf_small_fast
cp cmh_vcf_small.py ~/mybin/cmh_vcf_small
cp vcf-subset-fast.py ~/mybin/vcf-subset-fast
cp vcf-subset-fast-dup.py ~/mybin/vcf-subset-fast-dup
cp vcf-subset-freq.py ~/mybin/vcf-subset-freq
cp vcf-subset-freq-nopool.py ~/mybin/vcf-subset-freq-nopool
cp plot_bed_info_liber.py ~/mybin/plot_bed_info
cp plot_vcf_info_liber.py ~/mybin/plot_vcf_info
cp vcf2bed_cmh.sh ~/mybin/vcf2bed_cmh
cp plot_vcf_cmh_fast.sh ~/mybin/plot_vcf_cmh_fast
cp plot_vcf_cmh_fast_wide.sh ~/mybin/plot_vcf_cmh_fast_wide
cp plot_vcf_cmh_fast_wide_lowdpi.sh ~/mybin/plot_vcf_cmh_fast_wide_lowdpi
cp pfst.sh ~/mybin/pfst
cp pfst_nopool.sh ~/mybin/pfst_nopool
cp vcf_colnums.py ~/mybin/vcf_colnums
cp cybert_vcf_nolib.py ~/mybin/cybert_vcf_nolib
cp cybert_vcf_small_fast.py ~/mybin/cybert_vcf_small_fast
cp pfst2bed.py ~/mybin/pfst2bed
cp vcf2bed_pfst.sh ~/mybin/vcf2bed_pfst
cp plot_vcf_pfst_fast_wide_lowdpi.sh ~/mybin/plot_vcf_pfst_fast_wide_lowdpi
cp vcf2bed_cybert.sh ~/mybin/vcf2bed_cybert
cp plot_vcf_cybert_fast_wide_lowdpi.sh ~/mybin/plot_vcf_cybert_fast_wide_lowdpi
cp vcf_dens.sh ~/mybin/vcf_dens
cp vcf2bed_clean.sh ~/mybin/vcf2bed_clean
cp bed2png.sh ~/mybin/bed2png
cp combine_single_indivs_fast.py ~/mybin/combine_single_indivs_fast
cp combine_single_indivs.py ~/mybin/combine_single_indivs
cp vcf2sync.py ~/mybin/vcf2sync
cp combine_all_singles.py ~/mybin/combine_all_singles
cp combine_all_singles_replicates.py ~/mybin/combine_all_singles_replicates
cp split_pools.py ~/mybin/split_pools
