#!/bin/sh
set -e

BINDIR="${1}"

cp cmh_vcf_nolib.py "${BINDIR}/cmh_vcf_nolib"
cp cmh_vcf.py "${BINDIR}/cmh_vcf"
cp cmh_vcf_small_fast.py "${BINDIR}/cmh_vcf_small_fast"
cp cmh_vcf_small.py "${BINDIR}/cmh_vcf_small"
cp vcf-subset-fast.py "${BINDIR}/vcf-subset-fast"
cp vcf-subset-fast-dup.py "${BINDIR}/vcf-subset-fast-dup"
cp vcf-subset-freq.py "${BINDIR}/vcf-subset-freq"
cp vcf-subset-freq-nopool.py "${BINDIR}/vcf-subset-freq-nopool"
cp plot_bed_info.py "${BINDIR}/plot_bed_info"
cp plot_vcf_info.py "${BINDIR}/plot_vcf_info"
cp vcf2bed_cmh.sh "${BINDIR}/vcf2bed_cmh"
cp plot_vcf_cmh_fast.sh "${BINDIR}/plot_vcf_cmh_fast"
cp plot_vcf_cmh_fast_wide.sh "${BINDIR}/plot_vcf_cmh_fast_wide"
cp plot_vcf_cmh_fast_wide_lowdpi.sh "${BINDIR}/plot_vcf_cmh_fast_wide_lowdpi"
cp pfst.sh "${BINDIR}/pfst"
cp pfst_nopool.sh "${BINDIR}/pfst_nopool"
cp pfst_nopool_gz.sh "${BINDIR}/pfst_nopool_gz"
# go build pfst_nopool_gz.go
# cp pfst_nopool_gz "${BINDIR}/pfst_nopool_gz"
cp vcf_colnums.py "${BINDIR}/vcf_colnums"
cp cybert_vcf_nolib.py "${BINDIR}/cybert_vcf_nolib"
cp cybert_vcf_small_fast.py "${BINDIR}/cybert_vcf_small_fast"
cp pfst2bed.py "${BINDIR}/pfst2bed"
cp vcf2bed_pfst.sh "${BINDIR}/vcf2bed_pfst"
cp plot_vcf_pfst_fast_wide_lowdpi.sh "${BINDIR}/plot_vcf_pfst_fast_wide_lowdpi"
cp vcf2bed_cybert.sh "${BINDIR}/vcf2bed_cybert"
cp plot_vcf_cybert_fast_wide_lowdpi.sh "${BINDIR}/plot_vcf_cybert_fast_wide_lowdpi"
cp vcf_dens.sh "${BINDIR}/vcf_dens"
cp vcf2bed_clean.sh "${BINDIR}/vcf2bed_clean"
cp bed2png.sh "${BINDIR}/bed2png"
cp combine_single_indivs_fast.py "${BINDIR}/combine_single_indivs_fast"
cp combine_single_indivs.py "${BINDIR}/combine_single_indivs"
cp vcf2sync.py "${BINDIR}/vcf2sync"
cp combine_all_singles.py "${BINDIR}/combine_all_singles"
cp combine_all_singles_replicates.py "${BINDIR}/combine_all_singles_replicates"
cp split_pools.py "${BINDIR}/split_pools"
cp sync_filter.py "${BINDIR}/sync_filter"
go build space_vcf.go && cp space_vcf "${BINDIR}/space_vcf"
cp -p cmh_full.sh "${BINDIR}/cmh_full"
